version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: attendly-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: attendly
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - attendly-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: attendly-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/attendly?schema=public
      JWT_SECRET: your-super-secret-jwt-key-change-this-in-production
      FRONTEND_URL: http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - attendly-network
    volumes:
      - ./backend/src:/app/src:ro
    command: >
      sh -c "npx prisma migrate deploy &&
             npx prisma generate &&
             node src/index.js"

  # Frontend Next.js App
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    container_name: attendly-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:5000
    depends_on:
      - backend
    networks:
      - attendly-network

volumes:
  postgres_data:

networks:
  attendly-network:
    driver: bridge
